plugin: aws_ec2
regions:
  - us-east-1
  - us-west-2
hostnames:
  # Check for specific tags and dynamically select hostnames based on environment
  - "${AWS_INSTANCE_ENVIRONMENT}_dns-name"   # Selects the public DNS based on the environment variable
  - ip-address                             # Fallback to private IP if public DNS isn't available
  - private-ip                             # Use private IP for internal communication
  
env:
  # Define environment-specific variables for dynamic hostname resolution
  production: "prod_dns_name"
  staging: "stage_dns_name"
  development: "dev_dns_name"
  
filters:
  # Optional filter to select instances based on environment
  tag:Environment: "prod"  # Adjust to select instances based on the environment

group_by:
  # Group instances based on environment for different environment configurations
  "tag:Environment": environment_groups
