---
- name: Install and Configure HTTPD
  hosts: "_prodWebServer3,_prodWebServer4"
  become: true
  tasks:
    - name: Display current server details
      debug:
        msg: >
          Executing tasks on server:
          Inventory Hostname: {{ inventory_hostname }}
          Server Hostname: {{ ansible_hostname }}
          Private IP: {{ ansible_host }}

    - name: Update the system
      yum:
        name: "*"
        state: latest

    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start and enable HTTPD
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create the index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>ACS-Final-Assignment-Group1</title>
          </head>
          <body>
              <h1 style="text-align: center; color: blue;">ACS-Final-Project-Group1</h1>
              <h2 style="text-align: center; color: blue;">Created by Pooja, Poonam, Shailendra, and Arjoo</h2>
            <h3 style="text-align: center; color: blue;">Server Name: {{ inventory_hostname }}</h3>
              <div style="text-align: center;"> 
              <img src="https://group1-acs730finalproj-prod.s3.us-east-1.amazonaws.com/picture.jpg" width="600">
          </body>
          </html>

    - name: Ensure proper permissions for the web directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        recurse: yes
