name: TFLint Checks on Terraform Code

on:
  push:
    branches:
      - Staging
permissions: read-all

jobs:
  tflint-checks:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out Git Repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4.0.0
        name: Setup TFLint
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact --recursive
