name: Terraform Security Scan

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - prod

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install tfscan
      run: |
        curl -L https://github.com/accurics/terrascan/releases/latest/download/terrascan-linux-amd64 -o terrascan
        chmod +x terrascan
        sudo mv terrascan /usr/local/bin/

    - name: Run tfscan
      run: |
        terrascan scan -i terraform -d .
