name: TFLint Scan

on:
  push:
    branches:
      - Staging
      - Production

jobs:
  tflint_scan:
    name: "TFLint Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TFLint
        run: |
          curl -L -o tflint.zip https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip
          unzip tflint.zip
          chmod +x tflint
          sudo mv tflint /usr/local/bin/

      - name: Run TFLint scan
        run: tflint
